apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsthr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsthr
  template:
    metadata:
      labels:
        app: ngsthr
    spec:
      containers:
      - image: okteto.dev/ngsthr:latest
        name: ngsthr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a41a7391-db83-4738-ab9c-171f126bbe72"
        - name: Vless_Path
          value: "/vldhd555"
        - name: Vmess_UUID
          value: "a41a7391-db83-4738-ab9c-171f126bbe72"
        - name: Vmess_Path
          value: "/vm6cdv66"
        - name: Share_Path
          value: "/v2link"
